name: responsive_dashboard
description: "A responsive dashboard made with flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.2
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.3.13
  quds_ui_kit: ^0.0.7+10
  get: ^4.6.6
  flutter_adaptive_ui: ^0.8.0+1
  gap: ^3.0.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/  
